import math
import pygame

WIDTH, HEIGHT = 600, 600
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 120
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 1800
SCALE = WIDTH // NUM_RAYS
DIST = WIDTH / (2 * math.tan(HALF_FOV))
PROJ_COEF = 3 * DIST * 40